# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'yolov4_live_detectorEByCbj.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(792, 738)
        font = QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Prog_Title = QLabel(self.centralwidget)
        self.Prog_Title.setObjectName(u"Prog_Title")
        self.Prog_Title.setGeometry(QRect(220, 10, 381, 41))
        font1 = QFont()
        font1.setFamily(u"Agency FB")
        font1.setPointSize(20)
        self.Prog_Title.setFont(font1)
        self.Prog_Title.setLayoutDirection(Qt.LeftToRight)
        self.Prog_Title.setTextFormat(Qt.PlainText)
        self.Prog_Title.setAlignment(Qt.AlignCenter)
        self.index_input = QTextEdit(self.centralwidget)
        self.index_input.setObjectName(u"index_input")
        self.index_input.setGeometry(QRect(660, 470, 111, 41))
        self.index_label = QLabel(self.centralwidget)
        self.index_label.setObjectName(u"index_label")
        self.index_label.setGeometry(QRect(660, 450, 81, 21))
        font2 = QFont()
        font2.setPointSize(12)
        self.index_label.setFont(font2)
        self.SaveIndexBtn = QPushButton(self.centralwidget)
        self.SaveIndexBtn.setObjectName(u"SaveIndexBtn")
        self.SaveIndexBtn.setGeometry(QRect(660, 532, 111, 31))
        self.CapBtn = QPushButton(self.centralwidget)
        self.CapBtn.setObjectName(u"CapBtn")
        self.CapBtn.setGeometry(QRect(660, 600, 111, 23))
        self.CloseBtn = QPushButton(self.centralwidget)
        self.CloseBtn.setObjectName(u"CloseBtn")
        self.CloseBtn.setGeometry(QRect(660, 670, 111, 23))
        self.AboutBtn = QPushButton(self.centralwidget)
        self.AboutBtn.setObjectName(u"AboutBtn")
        self.AboutBtn.setGeometry(QRect(660, 700, 111, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 90, 416, 416))
        font3 = QFont()
        font3.setFamily(u"Agency FB")
        font3.setPointSize(26)
        font3.setBold(True)
        font3.setWeight(75)
        self.label.setFont(font3)
        self.label.setAutoFillBackground(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.GetObjSegmentBtn = QPushButton(self.centralwidget)
        self.GetObjSegmentBtn.setObjectName(u"GetObjSegmentBtn")
        self.GetObjSegmentBtn.setGeometry(QRect(660, 570, 111, 23))
        self.SelcPathBtn = QPushButton(self.centralwidget)
        self.SelcPathBtn.setObjectName(u"SelcPathBtn")
        self.SelcPathBtn.setGeometry(QRect(360, 580, 75, 23))
        self.path_label = QLabel(self.centralwidget)
        self.path_label.setObjectName(u"path_label")
        self.path_label.setGeometry(QRect(10, 580, 341, 20))
        self.path_label.setFont(font)
        self.status_label = QLabel(self.centralwidget)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(650, 30, 121, 311))
        self.status_label.setFont(font2)
        self.status_label.setAlignment(Qt.AlignCenter)
        self.fromFileBtn = QPushButton(self.centralwidget)
        self.fromFileBtn.setObjectName(u"fromFileBtn")
        self.fromFileBtn.setGeometry(QRect(660, 630, 111, 31))
        self.SelcPathBtn_segment = QPushButton(self.centralwidget)
        self.SelcPathBtn_segment.setObjectName(u"SelcPathBtn_segment")
        self.SelcPathBtn_segment.setGeometry(QRect(360, 550, 75, 23))
        self.segmentPath_label = QLabel(self.centralwidget)
        self.segmentPath_label.setObjectName(u"segmentPath_label")
        self.segmentPath_label.setGeometry(QRect(10, 550, 341, 20))
        self.segmentPath_label.setFont(font)
        self.detect_status = QLabel(self.centralwidget)
        self.detect_status.setObjectName(u"detect_status")
        self.detect_status.setGeometry(QRect(10, 520, 431, 20))
        self.detect_status.setAlignment(Qt.AlignCenter)
        self.videoStreamSizeLabel = QLabel(self.centralwidget)
        self.videoStreamSizeLabel.setObjectName(u"videoStreamSizeLabel")
        self.videoStreamSizeLabel.setGeometry(QRect(460, 490, 181, 16))
        self.MessageCheckBox = QCheckBox(self.centralwidget)
        self.MessageCheckBox.setObjectName(u"MessageCheckBox")
        self.MessageCheckBox.setGeometry(QRect(460, 430, 171, 19))
        self.MessageCheckBox.setChecked(False)
        self.runtimeCheckBox = QCheckBox(self.centralwidget)
        self.runtimeCheckBox.setObjectName(u"runtimeCheckBox")
        self.runtimeCheckBox.setGeometry(QRect(460, 460, 171, 19))
        self.runtimeCheckBox.setChecked(False)
        self.height_input = QTextEdit(self.centralwidget)
        self.height_input.setObjectName(u"height_input")
        self.height_input.setEnabled(False)
        self.height_input.setGeometry(QRect(560, 510, 61, 41))
        self.saveAddrBtn = QPushButton(self.centralwidget)
        self.saveAddrBtn.setObjectName(u"saveAddrBtn")
        self.saveAddrBtn.setGeometry(QRect(460, 300, 171, 28))
        self.openSocketCheckBox = QCheckBox(self.centralwidget)
        self.openSocketCheckBox.setObjectName(u"openSocketCheckBox")
        self.openSocketCheckBox.setGeometry(QRect(460, 170, 171, 19))
        self.openSocketCheckBox.setChecked(True)
        self.socketPortInput = QTextEdit(self.centralwidget)
        self.socketPortInput.setObjectName(u"socketPortInput")
        self.socketPortInput.setGeometry(QRect(580, 250, 51, 41))
        self.writeJsonCheckBox = QCheckBox(self.centralwidget)
        self.writeJsonCheckBox.setObjectName(u"writeJsonCheckBox")
        self.writeJsonCheckBox.setGeometry(QRect(460, 80, 171, 19))
        self.writeJsonCheckBox.setChecked(True)
        self.xLabel = QLabel(self.centralwidget)
        self.xLabel.setObjectName(u"xLabel")
        self.xLabel.setGeometry(QRect(540, 520, 21, 16))
        self.videoStreamCheckBox = QCheckBox(self.centralwidget)
        self.videoStreamCheckBox.setObjectName(u"videoStreamCheckBox")
        self.videoStreamCheckBox.setGeometry(QRect(460, 370, 171, 19))
        self.videoStreamCheckBox.setChecked(True)
        self.logJsonCheckBox = QCheckBox(self.centralwidget)
        self.logJsonCheckBox.setObjectName(u"logJsonCheckBox")
        self.logJsonCheckBox.setGeometry(QRect(460, 110, 171, 19))
        self.socketAddrLabel = QLabel(self.centralwidget)
        self.socketAddrLabel.setObjectName(u"socketAddrLabel")
        self.socketAddrLabel.setGeometry(QRect(460, 230, 181, 16))
        self.jsonLabel = QLabel(self.centralwidget)
        self.jsonLabel.setObjectName(u"jsonLabel")
        self.jsonLabel.setGeometry(QRect(460, 50, 171, 20))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setWeight(75)
        self.jsonLabel.setFont(font4)
        self.jsonLabel.setAlignment(Qt.AlignCenter)
        self.socketAddrInput = QTextEdit(self.centralwidget)
        self.socketAddrInput.setObjectName(u"socketAddrInput")
        self.socketAddrInput.setGeometry(QRect(460, 250, 111, 41))
        self.width_input = QTextEdit(self.centralwidget)
        self.width_input.setObjectName(u"width_input")
        self.width_input.setEnabled(False)
        self.width_input.setGeometry(QRect(470, 510, 61, 41))
        self.cvUISettingLabel = QLabel(self.centralwidget)
        self.cvUISettingLabel.setObjectName(u"cvUISettingLabel")
        self.cvUISettingLabel.setGeometry(QRect(460, 340, 171, 20))
        self.cvUISettingLabel.setFont(font4)
        self.cvUISettingLabel.setAlignment(Qt.AlignCenter)
        self.logSocketCheckBox = QCheckBox(self.centralwidget)
        self.logSocketCheckBox.setObjectName(u"logSocketCheckBox")
        self.logSocketCheckBox.setGeometry(QRect(460, 200, 171, 19))
        self.videoFlipCheckBox = QCheckBox(self.centralwidget)
        self.videoFlipCheckBox.setObjectName(u"videoFlipCheckBox")
        self.videoFlipCheckBox.setGeometry(QRect(460, 400, 171, 19))
        self.videoFlipCheckBox.setChecked(True)
        self.saveVideoSizeBtn = QPushButton(self.centralwidget)
        self.saveVideoSizeBtn.setObjectName(u"saveVideoSizeBtn")
        self.saveVideoSizeBtn.setEnabled(False)
        self.saveVideoSizeBtn.setGeometry(QRect(460, 560, 171, 28))
        self.socketLabel = QLabel(self.centralwidget)
        self.socketLabel.setObjectName(u"socketLabel")
        self.socketLabel.setGeometry(QRect(460, 140, 171, 20))
        self.socketLabel.setFont(font4)
        self.socketLabel.setAlignment(Qt.AlignCenter)
        self.confThreshold_label = QLabel(self.centralwidget)
        self.confThreshold_label.setObjectName(u"confThreshold_label")
        self.confThreshold_label.setGeometry(QRect(460, 600, 181, 16))
        self.NMSThreshold_label = QLabel(self.centralwidget)
        self.NMSThreshold_label.setObjectName(u"NMSThreshold_label")
        self.NMSThreshold_label.setGeometry(QRect(460, 650, 181, 16))
        self.saveThresholdBtn = QPushButton(self.centralwidget)
        self.saveThresholdBtn.setObjectName(u"saveThresholdBtn")
        self.saveThresholdBtn.setGeometry(QRect(460, 700, 181, 28))
        self.confThreshold_Input = QTextEdit(self.centralwidget)
        self.confThreshold_Input.setObjectName(u"confThreshold_Input")
        self.confThreshold_Input.setGeometry(QRect(580, 600, 61, 41))
        self.NMSInput = QTextEdit(self.centralwidget)
        self.NMSInput.setObjectName(u"NMSInput")
        self.NMSInput.setGeometry(QRect(580, 650, 61, 41))
        self.cfgFile_Label = QLabel(self.centralwidget)
        self.cfgFile_Label.setObjectName(u"cfgFile_Label")
        self.cfgFile_Label.setGeometry(QRect(10, 620, 301, 20))
        self.cfgFile_Label.setFont(font)
        self.namesFile_Label = QLabel(self.centralwidget)
        self.namesFile_Label.setObjectName(u"namesFile_Label")
        self.namesFile_Label.setGeometry(QRect(10, 660, 301, 20))
        self.namesFile_Label.setFont(font)
        self.weightsFile_Label = QLabel(self.centralwidget)
        self.weightsFile_Label.setObjectName(u"weightsFile_Label")
        self.weightsFile_Label.setGeometry(QRect(10, 700, 301, 20))
        self.weightsFile_Label.setFont(font)
        self.confValue_checkbox = QCheckBox(self.centralwidget)
        self.confValue_checkbox.setObjectName(u"confValue_checkbox")
        self.confValue_checkbox.setGeometry(QRect(660, 390, 111, 19))
        self.confValue_checkbox.setChecked(True)
        self.showBBox_checkbox = QCheckBox(self.centralwidget)
        self.showBBox_checkbox.setObjectName(u"showBBox_checkbox")
        self.showBBox_checkbox.setGeometry(QRect(660, 420, 111, 19))
        self.showBBox_checkbox.setChecked(True)
        self.showNames_checkbox = QCheckBox(self.centralwidget)
        self.showNames_checkbox.setObjectName(u"showNames_checkbox")
        self.showNames_checkbox.setGeometry(QRect(660, 360, 121, 19))
        self.showNames_checkbox.setChecked(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"YOLOv4-Tiny Real-Time Object Detection", None))
        self.Prog_Title.setText(QCoreApplication.translate("MainWindow", u"YOLOv4-Tiny Live Detector Ver 1.1", None))
        self.index_input.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0</span></p></body></html>", None))
        self.index_label.setText(QCoreApplication.translate("MainWindow", u"Index:", None))
        self.SaveIndexBtn.setText(QCoreApplication.translate("MainWindow", u"Save Pref.", None))
        self.CapBtn.setText(QCoreApplication.translate("MainWindow", u"Cap!", None))
        self.CloseBtn.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.AboutBtn.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Video Stream", None))
        self.GetObjSegmentBtn.setText(QCoreApplication.translate("MainWindow", u"Segment", None))
        self.SelcPathBtn.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.path_label.setText(QCoreApplication.translate("MainWindow", u"Select Cap Saving Path...", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.fromFileBtn.setText(QCoreApplication.translate("MainWindow", u"From File", None))
        self.SelcPathBtn_segment.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.segmentPath_label.setText(QCoreApplication.translate("MainWindow", u"Select Segment Saving Path...", None))
        self.detect_status.setText(QCoreApplication.translate("MainWindow", u"Detect Status", None))
        self.videoStreamSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Video Stream Size", None))
        self.MessageCheckBox.setText(QCoreApplication.translate("MainWindow", u"Show Message", None))
        self.runtimeCheckBox.setText(QCoreApplication.translate("MainWindow", u"Show RunTime", None))
        self.height_input.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">416</span></p></body></html>", None))
        self.saveAddrBtn.setText(QCoreApplication.translate("MainWindow", u"Save Address", None))
        self.openSocketCheckBox.setText(QCoreApplication.translate("MainWindow", u"Open Socket", None))
        self.socketPortInput.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">9999</span></p></body></html>", None))
        self.writeJsonCheckBox.setText(QCoreApplication.translate("MainWindow", u"Write JSON", None))
        self.xLabel.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.videoStreamCheckBox.setText(QCoreApplication.translate("MainWindow", u"Open Video Stream", None))
        self.logJsonCheckBox.setText(QCoreApplication.translate("MainWindow", u"Log JSON", None))
        self.socketAddrLabel.setText(QCoreApplication.translate("MainWindow", u"Socket Server Address", None))
        self.jsonLabel.setText(QCoreApplication.translate("MainWindow", u"JSON", None))
        self.socketAddrInput.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">127.0.0.1</span></p></body></html>", None))
        self.width_input.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">416</span></p></body></html>", None))
        self.cvUISettingLabel.setText(QCoreApplication.translate("MainWindow", u"OpenCV UI Settings", None))
        self.logSocketCheckBox.setText(QCoreApplication.translate("MainWindow", u"Log Socket Msg", None))
        self.videoFlipCheckBox.setText(QCoreApplication.translate("MainWindow", u"Video Flip", None))
        self.saveVideoSizeBtn.setText(QCoreApplication.translate("MainWindow", u"Save Video Size", None))
        self.socketLabel.setText(QCoreApplication.translate("MainWindow", u"Socket", None))
        self.confThreshold_label.setText(QCoreApplication.translate("MainWindow", u"confThreshold:", None))
        self.NMSThreshold_label.setText(QCoreApplication.translate("MainWindow", u"NMS Threshold:", None))
        self.saveThresholdBtn.setText(QCoreApplication.translate("MainWindow", u"Save Threshold", None))
        self.confThreshold_Input.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0.9</span></p></body></html>", None))
        self.NMSInput.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0.4</span></p></body></html>", None))
        self.cfgFile_Label.setText(QCoreApplication.translate("MainWindow", u".cfg File: network/1.cfg", None))
        self.namesFile_Label.setText(QCoreApplication.translate("MainWindow", u".names File: network/1.names", None))
        self.weightsFile_Label.setText(QCoreApplication.translate("MainWindow", u".weights File: network/1.weights", None))
        self.confValue_checkbox.setText(QCoreApplication.translate("MainWindow", u"Conf Value", None))
        self.showBBox_checkbox.setText(QCoreApplication.translate("MainWindow", u"Show BBox", None))
        self.showNames_checkbox.setText(QCoreApplication.translate("MainWindow", u"Object Names", None))
    # retranslateUi

